INSERT INTO stock (name, current_price, last_update) VALUES
('Apple Inc', 141.20, current_timestamp()),
('Microsoft Corp', 225.66, current_timestamp()),
('ABN AMRO', 7.972, current_timestamp()),
('Ajax', 15.76, current_timestamp()),
('ING Groep', 7.362, current_timestamp()),
('Takeaway.com', 94.92, current_timestamp()),
('TOMTOM N.V.', 9.45, current_timestamp()),
('Alphabet', 1870.01, current_timestamp()),
('Amazon.com Inc', 3279.14, current_timestamp()),
('Boeing', 200.88, current_timestamp()),
('Coca-Cola', 48.415, current_timestamp()),
('Facebook', 275.02, current_timestamp()),
('Ford Motor', 11.08, current_timestamp()),
('IBM', 118.34, current_timestamp()),
('Intel Corp', 54.91, current_timestamp()),
('Netflix Inc', 558.72, current_timestamp()),
('NVIDIA Corp', 539.715, current_timestamp()),
('Oracle Corp', 60.20, current_timestamp()),
('Qualcomm', 163.60, current_timestamp()),
('Walt Disney', 170.33, current_timestamp()),
('Tesla', 862, current_timestamp());
